### ISSUE TITLE
bug when I train cifar10_rnn_gate_rl_38

### ISSUE THREAD

**Issue by 13597862** [ucbdrive/skipnet#12]
Excuse me,I encountered the bug.Can you run the code using the command"python3 train_rl.py train cifar10_rnn_gate_rl_38 --resume resnet-38-rnn-sp-cifar10.pth.tar -d cifar10 --gate-type rnn
" normally?

The bug information lists as follow.
Traceback (most recent call last):
  File "train_rl.py", line 492, in <module>
    main()
  File "train_rl.py", line 121, in main
    run_training(args)
  File "train_rl.py", line 217, in run_training
    output, masks, probs = model(input_var)
  File "/home/wym/anaconda3/envs/python_auto/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wym/anaconda3/envs/python_auto/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 167, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/wym/anaconda3/envs/python_auto/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 177, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/wym/anaconda3/envs/python_auto/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/wym/anaconda3/envs/python_auto/lib/python3.6/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/wym/anaconda3/envs/python_auto/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/wym/anaconda3/envs/python_auto/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wym/skipnet-master/cifar/models.py", line 1243, in forward
    mask, gprob = self.control(gate_feature)
  File "/home/wym/anaconda3/envs/python_auto/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wym/skipnet-master/cifar/models.py", line 1136, in forward
    action = bi_prob.multinomial()
TypeError: multinomial() missing 1 required positional arguments: "num_samples"

**Comment by akinsanyaayomide** [comment]
Hello  @13597862 Have you been able to resolve this?
